### ISSUE TITLE
[ BUG ] FIX CI/CD deployment failures

### ISSUE THREAD

**Issue by yunhacandy** [IT-Cotato/9th-Growing-Pain-BE#15]
## 🛠️ Description for bug 
버그 관련 사항에 대해 작성해주세요.

### 어떤 버그인가요?

> git branch merge가 잘못되어서 일부 파일 누락

## 📝 Todo-lists
- [x] 실패 해결

**Comment by yunhacandy** [comment]
일단은 해결한거 같습니다.
현재 에러가 뜨는건 로그인 관련된 코드가 미완성이라 그런거 같습니다~

**Comment by nar0ng** [comment]
확인했습니다!

**Comment by yunhacandy** [comment]
내가 해냄...!!!!!!!!!!!

**Comment by nar0ng** [comment]
짱이에요 🫳🫳🫳🫳
